version: '3'
services:
  kafka1:
    image: "wurstmeister/kafka"
    container_name: kafka1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 2
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.21.191:9092
      KAFKA_ZOOKEEPER_CONNECT: 192.168.21.191:3181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092

  kafka2:
    image: wurstmeister/kafka
    container_name: kafka2
    ports:
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 2
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.21.191:9094
      KAFKA_ZOOKEEPER_CONNECT: 192.168.21.191:3181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9094


  kafka3:
    image: wurstmeister/kafka
    container_name: kafka3
    ports:
      - "9095:9095"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 2
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.21.191:9095
      KAFKA_ZOOKEEPER_CONNECT: 192.168.21.191:3181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9095
